##
## INSTRUCTIONS 
##  
## Instructions for updating .rda files in the package whitebox data directory
##
## Data sets: wbttools and wbttoolparameters
##
#
# 1. Make sure `whitebox` is using the version of the executable you would like parameter information for. Set it with `wbt_init(exe_path = ...)` as needed. 
# 
# 2. Run this R file. If it runs without error, new data sets `wbttools` and `wbttoolparameters` should be generated based on the output of `wbt_list_tools()`  
#
# 3. Install the package and inspect that the new data sets function and look as expected. Run R CMD check which will build the "data sets" vignette. If you manually knit the vignette in whiteboxR/vignettes/datasets.Rmd it should provide visual confirmation that things are in working order.
# 
# 4. Commit the changes to binary Rdata files: wbttools.rda, wbttoolparameters.rda and any corresponding changes to this file.
#
#  NOTE: these data sets are documented in R/whitebox-package.R and autogenerated files man/wbttools.Rd and man/wbttoolparameters.Rd
#
### Changelog ### 
# 
# - built 2021/08/24 with WhiteboxTools 1.5.0 agb
#
####

library(whitebox)
wbt_verbose(FALSE)

# parse the tools from wbt_list_tools (independent of internal dataset; dependent on binary version)
wlt <- wbt_list_tools()
x <- gsub("([A-Za-z0-9]+):.*|^All [0-9]+.*", "\\1", wlt)
y <- sapply(x[nchar(x) > 0], wbt_toolbox)
z <- gsub("[A-Za-z0-9]+:(.*)|^All [0-9]+.*", "\\1", wlt[nchar(x) > 0])

# this is just the WBT executables tool list, parsed to remove any empty lines
wbttools <- data.frame(tool_name = x[nchar(x) > 0], toolbox_name = y, description = z)

# this requires jsonlite, but uses the the WBT executable toolparameters argument
#  as wrapped by the package function wbt_tool_parameters()
.get_tool_params_from_binary <- function(tool_name) {
  
  if (!requireNamespace("jsonlite", quietly = TRUE)) {
    stop("please install the package 'jsonlite'", call. = FALSE)
  }
  
  json <- whitebox::wbt_tool_parameters(tool_name, quiet = TRUE)
  
  # TODO: store as Rda file within package, update with latest binary, run on prior binaries? version argument
  params <- jsonlite::parse_json(json, simplifyVector = FALSE)$parameters
  
  # extract parameter label types
  ## TODO: improve this
  paramtypes <- lapply(params, function(x) x$parameter_type)
  paramdetails <- lapply(unlist(paramtypes, recursive = FALSE), function(x) {
    xlabl <- paste0(names(x))
    paste0(c(xlabl, paste0(x, collapse=", ")), collapse=": ")
  })
  psub <- paste(names(paramtypes)[nchar(paramtypes) > 0], paramtypes[nchar(paramtypes) > 0])
    
  # parse it again to get the data frame structure
  params <- jsonlite::parse_json(json, simplifyVector = TRUE)$parameters
  
  # don't return the nested parameter_type
  params$parameter_type <- NULL
  
  # return two new fields generalized "parameter_class" ~parameter type/kinds, primary datatypes
  #                       and details "parameter_details" For files any details; 
  #                       For OptionList any default options, comma separated
  params$parameter_class <- names(paramdetails)
  params$parameter_detail <- as.character(paramdetails)
  
  # allowed flags in package calls (i/o and other shorthand not allowed)
  params$pkgflags <- vapply(params$flags, function(x) paste0(sort(x[grep("--[a-z]{3}", x)]), collapse=", "), character(1))
  
  # extract labels
  params$argument_name <- sapply(params$pkgflags, function(x) paste0(gsub("--", "", x[grep("--", x)]), collapse=", "))
  
  # handle special cases so argument_name matches wbt_ functions
  ## see: subset(params, grepl(',', params$pkgflags))
  params$argument_name <- gsub("(dem), input|dist, (radius)|out_html, (output)|base, (input)|clip, (stdev)", "\\1\\2\\3\\4\\5", params$argument_name)
  
  # reduced subset of flags used internally to process $flags
  params$pkgflags <- NULL
  
  # classify parameters as input or output based on i/o $flags
  params$is_input <- sapply(params$flags, function(x) any(grepl("^-i$$", x)))
  params$is_output <- sapply(params$flags, function(x) any(grepl("^-o$", x)))
  params$flags <- sapply(params$flags, paste0, collapse= ", ")
  params
} 

# iterate over tool name, getting parameters from WBT binary JSON output
wbttoolparameters <- do.call('rbind', lapply(seq_along(wbttools$tool_name), function(i) {
  x <- wbttools$tool_name[i]
  
  data.frame(tool_name = x, toolbox_name = wbttools$toolbox_name[i], .get_tool_params_from_binary(x)) 
}))
rownames(wbttools) <- NULL
rownames(wbttoolparameters) <- NULL

# list all functions in the whitebox package currently installed
wbtfunction <- ls('package:whitebox', "wbt_")

# use the new wbttool parameters, and "cleaned" function names (remove wbt_ prefix and underscores)
wbtfunction_clean <- gsub("_", "", whitebox:::wbt_internal_tool_name(wbtfunction))
idx1 <- match(tolower(wbttools$tool_name), wbtfunction_clean)
idx2 <- match(tolower(wbttoolparameters$tool_name), wbtfunction_clean)

# add $function_name to both datasets
wbttools <- data.frame(function_name = wbtfunction[idx1[which(!is.na(idx1))]], wbttools)
wbttoolparameters <- data.frame(function_name = wbtfunction[idx2[which(!is.na(idx2))]], wbttoolparameters)

# parse version
wbtvs <- gsub(".*v([0-9.\\-]+\\b).*", "\\1", wbt_version()[1])
# wbtvs
# #> [1] "1.5.0"
stopifnot(wbtvs > "1.0.0")

attr(wbttools, 'version') <- wbtvs
attr(wbttoolparameters, 'version') <- wbtvs

# cleanup (trim whitespace on character variables)
wbttools[] <- lapply(wbttools, function(x) if(is.character(x)) return(trimws(x)) else x)
wbttoolparameters[] <- lapply(wbttoolparameters, function(x) if(is.character(x)) return(trimws(x)) else x)

# overwrite datasets with new data
usethis::use_data(wbttools, overwrite = TRUE)
usethis::use_data(wbttoolparameters, overwrite = TRUE)
